"use client";

/**
 * Confidence badge for AI-generated content.
 * Levels: high (green), medium (amber), low (red)
 * Rule-based heuristic: sections with direct document extraction = high,
 * inferred/estimated data = medium, speculative data = low.
 */
export function ConfidenceBadge({ level = "medium", className = "" }) {
  const config = {
    high: { label: "High confidence", bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20" },
    medium: { label: "Medium confidence", bg: "bg-amber-500/10", text: "text-amber-400", border: "border-amber-500/20" },
    low: { label: "Low confidence", bg: "bg-red-500/10", text: "text-red-400", border: "border-red-500/20" },
  };
  const c = config[level] || config.medium;

  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider border ${c.bg} ${c.text} ${c.border} ${className}`}
      title={`AI confidence: ${level}. This output was generated by AI and should be verified.`}
    >
      <svg className="w-2.5 h-2.5" fill="currentColor" viewBox="0 0 20 20">
        <path fillRule="evenodd" d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-7-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM9 9a.75.75 0 0 0 0 1.5h.253a.25.25 0 0 1 .244.304l-.459 2.066A1.75 1.75 0 0 0 10.747 15H11a.75.75 0 0 0 0-1.5h-.253a.25.25 0 0 1-.244-.304l.459-2.066A1.75 1.75 0 0 0 9.253 9H9Z" clipRule="evenodd" />
      </svg>
      {c.label}
    </span>
  );
}

/**
 * Inline disclaimer for AI-generated sections.
 * Variants: subtle (small text), standard (with icon), verify (stronger wording)
 */
export function AIDisclaimer({ variant = "subtle", className = "" }) {
  const messages = {
    subtle: "AI-generated analysis. Verify before acting.",
    standard: "This section was generated by AI based on the uploaded document. Review outputs and verify independently before making business decisions.",
    verify: "AI-estimated data. These insights are inferred from the tender document and may not reflect actual market conditions. Verify independently.",
  };

  if (variant === "subtle") {
    return (
      <p className={`text-[11px] flex items-center gap-1.5 ${className}`} style={{ color: "var(--text-muted)" }}>
        <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 0 0-2.455 2.456Z" />
        </svg>
        {messages.subtle}
      </p>
    );
  }

  return (
    <div
      className={`flex items-start gap-2.5 px-4 py-3 rounded-xl text-xs leading-relaxed ${className}`}
      style={{ background: "var(--bg-subtle)", border: "1px solid var(--border-primary)", color: "var(--text-muted)" }}
    >
      <svg className="w-4 h-4 shrink-0 mt-0.5" style={{ color: "var(--text-muted)" }} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 0 0-2.455 2.456Z" />
      </svg>
      <span>{messages[variant]}</span>
    </div>
  );
}

/**
 * Assigns a heuristic confidence level to each analysis section.
 * High = directly extracted from document text
 * Medium = analyzed/interpreted from document
 * Low = inferred/speculated beyond document content
 */
export function getSectionConfidence(sectionName) {
  const levels = {
    // High confidence — extracted directly from document
    summary: "high",
    requirements: "high",
    keyDates: "high",
    evaluationCriteria: "high",
    financialRequirements: "high",

    // Medium confidence — analyzed/interpreted
    complianceAnalysis: "medium",
    riskRadar: "medium",
    bidScore: "medium",

    // Low confidence — speculative/inferred
    winProbability: "low",
    competitorIntelligence: "low",
    pricingAdvisor: "low",
  };
  return levels[sectionName] || "medium";
}
