import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ── DESIGN TOKENS ──
const NAVY = [26, 35, 50];
const WHITE = [255, 255, 255];
const GREEN = [34, 197, 94];
const AMBER = [245, 158, 11];
const RED = [239, 68, 68];
const TEAL = [13, 148, 136];
const DARK = [30, 30, 30];
const SECONDARY = [120, 130, 145];
const CARD_BORDER = [226, 232, 240];
const CARD_BG = [255, 255, 255];
const M = 15; // page margin
const TABLE_HEAD_BG = [241, 245, 249];

function scoreColor(score) {
  if (score >= 70) return GREEN;
  if (score >= 40) return AMBER;
  return RED;
}

function severityColor(s) {
  switch ((s || "").toUpperCase()) {
    case "CRITICAL": return RED;
    case "HIGH": return RED;
    case "MEDIUM": return AMBER;
    case "LOW": return GREEN;
    default: return SECONDARY;
  }
}

function cap(s) {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : "";
}

function truncate(s, max) {
  if (!s) return "";
  return s.length > max ? s.substring(0, max - 1) + "\u2026" : s;
}

// ── HEADER BAR (every page) ──
function drawHeader(doc) {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pw, 14, "F");
  // Teal accent line
  doc.setFillColor(...TEAL);
  doc.rect(0, 14, pw, 0.8, "F");
  // Logo
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...WHITE);
  doc.text("Bidlyze", M, 9.5);
  // Tagline
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 190, 200);
  doc.text("AI Tender Analysis Report", M + 22, 9.5);
  // Date
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  doc.setFontSize(7);
  doc.setTextColor(180, 190, 200);
  doc.text(dateStr, pw - M, 9.5, { align: "right" });
}

// ── FOOTER (every page) ──
function drawFooters(doc) {
  const pageCount = doc.getNumberOfPages();
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...CARD_BORDER);
    doc.setLineWidth(0.3);
    doc.line(M, ph - 10, pw - M, ph - 10);
    doc.setFontSize(7);
    doc.setTextColor(...SECONDARY);
    doc.text("Generated by Bidlyze \u2014 bidlyze.com", M, ph - 6);
    doc.text(`Page ${i} of ${pageCount}`, pw - M, ph - 6, { align: "right" });
  }
}

// ── SECTION HEADING ──
function sectionHead(doc, title, y) {
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text(title, M, y);
  const tw = doc.getTextWidth(title);
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.6);
  doc.line(M, y + 1.5, M + tw + 2, y + 1.5);
  // Faint full-width line
  doc.setDrawColor(...CARD_BORDER);
  doc.setLineWidth(0.2);
  const pw = doc.internal.pageSize.getWidth();
  doc.line(M + tw + 4, y + 1.5, pw - M, y + 1.5);
  return y + 8;
}

// ── CARD BOX ──
function drawCard(doc, x, y, w, h) {
  doc.setFillColor(...CARD_BG);
  doc.setDrawColor(...CARD_BORDER);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");
}

// ── SCORE GAUGE (arc-style) ──
function drawGauge(doc, cx, cy, r, score, maxScore, label) {
  const pct = Math.min(score / maxScore, 1);
  const color = scoreColor(score);
  // Background circle
  doc.setDrawColor(230, 235, 240);
  doc.setLineWidth(2.5);
  doc.circle(cx, cy, r, "S");
  // Colored arc (simulated with thick arc segments)
  doc.setDrawColor(...color);
  doc.setLineWidth(2.5);
  const segments = Math.round(pct * 36);
  for (let i = 0; i < segments; i++) {
    const a1 = (-90 + i * 10) * (Math.PI / 180);
    const a2 = (-90 + (i + 1) * 10) * (Math.PI / 180);
    const x1 = cx + r * Math.cos(a1);
    const y1 = cy + r * Math.sin(a1);
    const x2 = cx + r * Math.cos(a2);
    const y2 = cy + r * Math.sin(a2);
    doc.line(x1, y1, x2, y2);
  }
  // Score text
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...color);
  const st = String(score);
  doc.text(st, cx - doc.getTextWidth(st) / 2, cy + 2);
  // Sub label
  doc.setFontSize(6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SECONDARY);
  const sub = `/ ${maxScore}`;
  doc.text(sub, cx - doc.getTextWidth(sub) / 2, cy + 6.5);
  // Label below
  if (label) {
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(label, cx - doc.getTextWidth(label) / 2, cy + r + 5);
  }
}

// ── HORIZONTAL COLORED BAR ──
function drawBar(doc, x, y, maxW, pct, color, h) {
  h = h || 4;
  doc.setFillColor(235, 240, 245);
  doc.roundedRect(x, y, maxW, h, 1.5, 1.5, "F");
  if (pct > 0) {
    doc.setFillColor(...color);
    doc.roundedRect(x, y, Math.max(maxW * pct, 3), h, 1.5, 1.5, "F");
  }
}

// ── STATUS DOT ──
function drawDot(doc, x, y, color, r) {
  r = r || 1.5;
  doc.setFillColor(...color);
  doc.circle(x, y, r, "F");
}

// ── BADGE ──
function drawBadge(doc, text, x, y, color) {
  const tw = doc.getTextWidth(text);
  const bw = tw + 6;
  doc.setFillColor(...color);
  doc.roundedRect(x, y, bw, 7, 2, 2, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...WHITE);
  doc.text(text, x + bw / 2 - tw / 2, y + 5);
  return bw;
}

// ════════════════════════════════════════════════
// MAIN EXPORT
// ════════════════════════════════════════════════
export function exportPDF(analysis, fileName) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const cw = pw - M * 2; // content width

  const {
    summary, requirements, complianceAnalysis, riskRadar, keyDates,
    evaluationCriteria, bidScore, winProbability,
    competitorIntelligence, pricingAdvisor,
  } = analysis || {};

  // ════════════════════════════════════════════════
  // PAGE 1 — EXECUTIVE DASHBOARD
  // ════════════════════════════════════════════════
  drawHeader(doc);
  let y = 20;

  // ── Project Info Bar ──
  y = sectionHead(doc, "Executive Dashboard", y);

  const infoItems = [
    ["Project", summary?.projectName],
    ["Authority", summary?.issuingAuthority],
    ["Reference", summary?.tenderReference],
    ["Sector", summary?.sector],
    ["Location", summary?.location],
    ["Deadline", summary?.submissionDeadline],
    ["Value", summary?.estimatedValue ? `${summary.currency || ""} ${summary.estimatedValue}`.trim() : null],
    ["Duration", summary?.projectDuration],
  ];

  drawCard(doc, M, y, cw, 24);
  // 2-row grid: Top row = first 4 items, Bottom row = last 4 items
  const colW = cw / 4;
  for (let i = 0; i < infoItems.length; i++) {
    const [label, value] = infoItems[i];
    const col = i % 4;
    const row = Math.floor(i / 4);
    const cx = M + 4 + col * colW;
    const cy = y + 4 + row * 11;
    doc.setFontSize(6.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...SECONDARY);
    doc.text(label.toUpperCase(), cx, cy);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    doc.text(truncate(value || "N/A", 24), cx, cy + 4.5);
  }
  y += 28;

  // ── Bid Score + Win Probability Row ──
  const gaugeRowY = y;
  const gaugeCardW = cw * 0.32;
  const wpCardW = cw * 0.32;
  const stratCardW = cw - gaugeCardW - wpCardW - 6;

  // Bid Score Gauge
  if (bidScore) {
    drawCard(doc, M, gaugeRowY, gaugeCardW, 48);
    const score = bidScore.score ?? 0;
    drawGauge(doc, M + gaugeCardW / 2, gaugeRowY + 20, 12, score, 100, null);
    // Recommendation badge
    const rec = bidScore.recommendation || "N/A";
    const isBid = rec === "BID";
    const badgeColor = isBid ? GREEN : rec === "NO-BID" ? RED : AMBER;
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const badgeText = rec;
    drawBadge(doc, badgeText, M + gaugeCardW / 2 - doc.getTextWidth(badgeText) / 2 - 3, gaugeRowY + 35, badgeColor);
    // One-line rationale
    if (bidScore.reasoning) {
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...SECONDARY);
      const rationale = truncate(bidScore.reasoning, 60);
      const rl = doc.splitTextToSize(rationale, gaugeCardW - 8);
      doc.text(rl, M + 4, gaugeRowY + 44);
    }
    // Label
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("BID SCORE", M + 4, gaugeRowY + 6);
  }

  // Win Probability
  if (winProbability) {
    const wpX = M + gaugeCardW + 3;
    drawCard(doc, wpX, gaugeRowY, wpCardW, 48);
    const wp = winProbability.overall ?? 0;
    drawGauge(doc, wpX + wpCardW / 2, gaugeRowY + 20, 12, wp, 100, null);
    // Position badge
    const pos = cap(winProbability.competitivePosition || "");
    const posColor = pos === "Strong" ? GREEN : pos === "Moderate" ? AMBER : RED;
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    drawBadge(doc, pos || "N/A", wpX + wpCardW / 2 - doc.getTextWidth(pos || "N/A") / 2 - 3, gaugeRowY + 35, posColor);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("WIN PROBABILITY", wpX + 4, gaugeRowY + 6);
    // % label on gauge
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY);
    doc.text("%", wpX + wpCardW / 2 + 7, gaugeRowY + 22);
  }

  // Strategy Recommendation box
  const stratX = M + gaugeCardW + wpCardW + 6;
  drawCard(doc, stratX, gaugeRowY, stratCardW, 48);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("STRATEGY", stratX + 4, gaugeRowY + 6);
  if (winProbability?.strategyRecommendation) {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    const sl = doc.splitTextToSize(winProbability.strategyRecommendation, stratCardW - 8);
    doc.text(sl.slice(0, 7), stratX + 4, gaugeRowY + 12);
  }

  y = gaugeRowY + 52;

  // ── Strengths & Risks Columns ──
  const halfW = (cw - 3) / 2;
  const strengths = (winProbability?.strengths || []).slice(0, 3);
  const risks = (riskRadar?.showstoppers || []).slice(0, 3);
  // If no showstoppers, use top risks from categories
  const topRisks = risks.length > 0 ? risks : (() => {
    const all = [];
    for (const cat of (riskRadar?.categories || [])) {
      for (const r of (cat.risks || [])) all.push(r.risk || r);
    }
    return all.slice(0, 3);
  })();

  // Strengths card
  drawCard(doc, M, y, halfW, 28);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GREEN);
  doc.text("STRENGTHS", M + 4, y + 5);
  let sy = y + 10;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);
  for (const s of strengths) {
    drawDot(doc, M + 6, sy - 0.5, GREEN);
    doc.text(truncate(s, 55), M + 10, sy);
    sy += 5.5;
  }
  if (strengths.length === 0) {
    doc.setFontSize(7);
    doc.setTextColor(...SECONDARY);
    doc.text("No strengths identified", M + 10, y + 12);
  }

  // Risks card
  const riskX = M + halfW + 3;
  drawCard(doc, riskX, y, halfW, 28);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...RED);
  doc.text("KEY RISKS", riskX + 4, y + 5);
  let ry = y + 10;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);
  for (const r of topRisks) {
    const rText = typeof r === "string" ? r : r?.risk || "";
    drawDot(doc, riskX + 6, ry - 0.5, RED);
    doc.text(truncate(rText, 55), riskX + 10, ry);
    ry += 5.5;
  }
  if (topRisks.length === 0) {
    doc.setFontSize(7);
    doc.setTextColor(...SECONDARY);
    doc.text("No major risks identified", riskX + 10, y + 12);
  }

  y += 32;

  // ── Evaluation Criteria Bar ──
  if (evaluationCriteria?.length > 0) {
    drawCard(doc, M, y, cw, 14);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("EVALUATION CRITERIA", M + 4, y + 5);
    let ex = M + 4;
    const barY = y + 8;
    const totalW = cw - 8;
    const colors = [TEAL, GREEN, AMBER, [59, 130, 246], [168, 85, 247]];
    for (let i = 0; i < evaluationCriteria.length && i < 5; i++) {
      const ec = evaluationCriteria[i];
      const wStr = (ec.weight || "").replace(/[^0-9]/g, "");
      const wNum = parseInt(wStr) || Math.round(100 / evaluationCriteria.length);
      const segW = (wNum / 100) * totalW;
      const col = colors[i % colors.length];
      doc.setFillColor(...col);
      if (i === 0) {
        doc.roundedRect(ex, barY, segW, 4, 1.5, 0, "F");
      } else if (i === evaluationCriteria.length - 1) {
        doc.roundedRect(ex, barY, segW, 4, 0, 1.5, "F");
      } else {
        doc.rect(ex, barY, segW, 4, "F");
      }
      // Label
      doc.setFontSize(5.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...WHITE);
      const label = `${truncate(ec.criterion, 12)} ${wNum}%`;
      if (segW > 15) {
        doc.text(label, ex + 2, barY + 3);
      }
      ex += segW;
    }
  }

  // ════════════════════════════════════════════════
  // PAGE 2 — SCORING & REQUIREMENTS
  // ════════════════════════════════════════════════
  doc.addPage();
  drawHeader(doc);
  y = 20;
  y = sectionHead(doc, "Scoring Breakdown", y);

  // Factor bars
  if (winProbability?.factors?.length > 0) {
    const barMaxW = cw * 0.4;
    for (const f of winProbability.factors) {
      const score = f.score ?? 0;
      const pct = score / 100;
      const color = scoreColor(score);
      // Factor name
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text(truncate(f.factor || "", 25), M, y + 3);
      // Score value
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...color);
      const scoreStr = String(score);
      doc.text(scoreStr, M + 50, y + 3);
      // Bar
      drawBar(doc, M + 58, y, barMaxW, pct, color);
      // Reasoning
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...SECONDARY);
      doc.text(truncate(f.reasoning || "", 55), M + 58 + barMaxW + 4, y + 3);
      y += 8;
    }
  }

  y += 6;

  // ── Requirements Section ──
  y = sectionHead(doc, requirements?.length > 0 ? `Requirements (${requirements.length})` : "Requirements", y);

  if (requirements?.length > 0) {
    const reqTable = autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [["Requirement", "Category", "Priority", "Status"]],
      body: requirements.map((r) => [
        truncate(r.requirement || "", 50),
        r.category || "",
        r.priority || "",
        r.mandatory ? "Mandatory" : "Optional",
      ]),
      headStyles: {
        fillColor: TABLE_HEAD_BG,
        textColor: DARK,
        fontStyle: "bold",
        fontSize: 8,
        cellPadding: 3,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: DARK,
        cellPadding: 2.5,
      },
      alternateRowStyles: { fillColor: [252, 253, 255] },
      columnStyles: {
        0: { cellWidth: "auto" },
        1: { cellWidth: 28 },
        2: { cellWidth: 20, halign: "center" },
        3: { cellWidth: 22, halign: "center" },
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 2) {
          data.cell.styles.textColor = severityColor(data.cell.raw);
          data.cell.styles.fontStyle = "bold";
        }
        if (data.section === "body" && data.column.index === 3) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.textColor = data.cell.raw === "Mandatory" ? RED : GREEN;
        }
      },
      didDrawCell: (data) => {
        // Draw status dot before priority text
        if (data.section === "body" && data.column.index === 2) {
          const raw = (data.cell.raw || "").toUpperCase();
          const dotColor = raw === "HIGH" ? RED : raw === "MEDIUM" ? AMBER : GREEN;
          drawDot(doc, data.cell.x + 3, data.cell.y + data.cell.height / 2, dotColor, 1.2);
        }
      },
    });
    y = (reqTable?.finalY || y + 10) + 4;

    // Count bar
    const mandatory = requirements.filter((r) => r.mandatory).length;
    const optional = requirements.length - mandatory;
    drawCard(doc, M, y, cw, 8);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(`Total: ${requirements.length}`, M + 4, y + 5.5);
    doc.setTextColor(...RED);
    doc.text(`Mandatory: ${mandatory}`, M + 35, y + 5.5);
    doc.setTextColor(...GREEN);
    doc.text(`Optional: ${optional}`, M + 65, y + 5.5);
  }

  // ════════════════════════════════════════════════
  // PAGE 3 — COMPLIANCE & RISK
  // ════════════════════════════════════════════════
  doc.addPage();
  drawHeader(doc);
  y = 20;
  y = sectionHead(doc, "Compliance Gap Analysis", y);

  if (complianceAnalysis) {
    // Compliance score + summary stats row
    const compScore = complianceAnalysis.overallComplianceScore ?? 0;
    const compColor = scoreColor(compScore);
    drawCard(doc, M, y, cw, 14);
    // Score gauge mini
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...compColor);
    doc.text(`${compScore}%`, M + 6, y + 9.5);
    // Stats
    if (complianceAnalysis.summary) {
      const cs = complianceAnalysis.summary;
      const stats = [
        [`Total: ${cs.totalItems ?? 0}`, DARK],
        [`Compliant: ${cs.compliant ?? 0}`, GREEN],
        [`Gaps: ${cs.gaps ?? 0}`, AMBER],
        [`Critical: ${cs.critical ?? 0}`, RED],
      ];
      let sx = M + 35;
      for (const [text, color] of stats) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...color);
        doc.text(text, sx, y + 9.5);
        sx += doc.getTextWidth(text) + 8;
      }
    }
    y += 18;

    // Gap/At-risk items only as cards
    const gapItems = (complianceAnalysis.items || []).filter((c) => c.status !== "compliant");
    if (gapItems.length > 0) {
      const gapTable = autoTable(doc, {
        startY: y,
        margin: { left: M, right: M },
        head: [["Issue", "Severity", "Action Required", "Owner", "Timeline"]],
        body: gapItems.map((c) => [
          c.item || "",
          cap(c.severity || ""),
          c.remediation || "",
          c.owner || "TBD",
          c.timeToRemediate || "",
        ]),
        headStyles: {
          fillColor: TABLE_HEAD_BG,
          textColor: DARK,
          fontStyle: "bold",
          fontSize: 8,
          cellPadding: 3,
        },
        bodyStyles: {
          fontSize: 8,
          textColor: DARK,
          cellPadding: 2.5,
        },
        columnStyles: {
          0: { cellWidth: "auto" },
          1: { cellWidth: 18, halign: "center" },
          2: { cellWidth: 40 },
          3: { cellWidth: 22 },
          4: { cellWidth: 22 },
        },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 1) {
            data.cell.styles.fontStyle = "bold";
            data.cell.styles.textColor = severityColor(data.cell.raw);
          }
          if (data.section === "body") {
            const item = gapItems[data.row.index];
            if (item?.status === "gap") data.cell.styles.fillColor = [254, 242, 242];
            else data.cell.styles.fillColor = [255, 251, 235];
          }
        },
      });
      y = (gapTable?.finalY || y + 10) + 6;
    } else {
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...GREEN);
      doc.text("All compliance items are in good standing.", M, y + 4);
      y += 10;
    }
  }

  // ── Risk Radar ──
  y = sectionHead(doc, "Risk Radar", y);

  if (riskRadar) {
    const riskScore = riskRadar.riskScore ?? 0;
    const riskColor = riskScore >= 75 ? RED : riskScore >= 50 ? AMBER : riskScore >= 25 ? AMBER : GREEN;

    // Risk score + level badge
    drawCard(doc, M, y, cw, 14);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...riskColor);
    doc.text(`${riskScore}/100`, M + 6, y + 9.5);
    const levelText = cap(riskRadar.overallRiskLevel || "") + " Risk";
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    drawBadge(doc, levelText, M + 40, y + 3.5, riskColor);
    y += 18;

    // Showstoppers box
    if (riskRadar.showstoppers?.length > 0) {
      const ssH = Math.min(riskRadar.showstoppers.length * 6 + 8, 30);
      doc.setFillColor(254, 242, 242);
      doc.setDrawColor(...RED);
      doc.setLineWidth(0.5);
      doc.roundedRect(M, y, cw, ssH, 2, 2, "FD");
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...RED);
      doc.text("SHOWSTOPPERS", M + 4, y + 5);
      let ssy = y + 10;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      for (const s of riskRadar.showstoppers.slice(0, 3)) {
        drawDot(doc, M + 6, ssy - 0.5, RED);
        doc.text(truncate(s, 80), M + 10, ssy);
        ssy += 5.5;
      }
      y += ssH + 4;
    }

    // Top 3 mitigations
    const allRisks = [];
    for (const cat of (riskRadar.categories || [])) {
      for (const r of (cat.risks || [])) {
        allRisks.push({ ...r, category: cat.category });
      }
    }

    if (allRisks.length > 0) {
      const ph = doc.internal.pageSize.getHeight();
      if (y > ph - 50) { doc.addPage(); drawHeader(doc); y = 20; }

      const riskTable = autoTable(doc, {
        startY: y,
        margin: { left: M, right: M },
        head: [["Risk", "Severity", "Likelihood", "Mitigation"]],
        body: allRisks.slice(0, 8).map((r) => [
          r.risk || "",
          cap(r.severity || ""),
          cap(r.likelihood || ""),
          truncate(r.mitigation || "", 50),
        ]),
        headStyles: {
          fillColor: TABLE_HEAD_BG,
          textColor: DARK,
          fontStyle: "bold",
          fontSize: 8,
          cellPadding: 3,
        },
        bodyStyles: {
          fontSize: 8,
          textColor: DARK,
          cellPadding: 2.5,
        },
        alternateRowStyles: { fillColor: [252, 253, 255] },
        columnStyles: {
          0: { cellWidth: "auto" },
          1: { cellWidth: 20, halign: "center" },
          2: { cellWidth: 22, halign: "center" },
          3: { cellWidth: 50 },
        },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 1) {
            data.cell.styles.fontStyle = "bold";
            data.cell.styles.textColor = severityColor(data.cell.raw);
          }
          if (data.section === "body" && data.column.index === 2) {
            data.cell.styles.fontStyle = "bold";
            const raw = (data.cell.raw || "").toLowerCase();
            if (raw === "certain" || raw === "likely") data.cell.styles.textColor = RED;
            else if (raw === "possible") data.cell.styles.textColor = AMBER;
            else data.cell.styles.textColor = GREEN;
          }
        },
      });
      y = (riskTable?.finalY || y + 10) + 4;
    }
  }

  // ════════════════════════════════════════════════
  // PAGE 4 — COMPETITOR & PRICING
  // ════════════════════════════════════════════════
  doc.addPage();
  drawHeader(doc);
  y = 20;
  y = sectionHead(doc, "Competitor Intelligence", y);

  if (competitorIntelligence?.estimatedCompetitors?.length > 0) {
    const competitors = competitorIntelligence.estimatedCompetitors.slice(0, 4);
    const cardW = (cw - (competitors.length - 1) * 3) / competitors.length;

    for (let i = 0; i < competitors.length; i++) {
      const c = competitors[i];
      const cx = M + i * (cardW + 3);
      drawCard(doc, cx, y, cardW, 40);

      // Name
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text(truncate(c.name || "Competitor", 18), cx + 3, y + 6);

      // Type
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...SECONDARY);
      doc.text(cap(c.type || ""), cx + 3, y + 10.5);

      // Threat level visual
      const threat = (c.threatLevel || "").toLowerCase();
      const threatColor = threat === "high" ? RED : threat === "medium" ? AMBER : GREEN;
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...threatColor);
      doc.text("THREAT", cx + 3, y + 16);
      drawBar(doc, cx + 18, y + 13.5, cardW - 22, threat === "high" ? 0.9 : threat === "medium" ? 0.6 : 0.3, threatColor, 3);

      // Strength
      doc.setFontSize(6);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...GREEN);
      doc.text("+", cx + 3, y + 22);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      doc.setFontSize(6.5);
      const str = (c.strengths || [])[0] || "N/A";
      const strLines = doc.splitTextToSize(truncate(str, 40), cardW - 10);
      doc.text(strLines[0] || "", cx + 7, y + 22);

      // Weakness
      doc.setFontSize(6);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...RED);
      doc.text("-", cx + 4, y + 27);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      doc.setFontSize(6.5);
      const wk = (c.weaknesses || [])[0] || "N/A";
      const wkLines = doc.splitTextToSize(truncate(wk, 40), cardW - 10);
      doc.text(wkLines[0] || "", cx + 7, y + 27);

      // Approach
      doc.setFontSize(6);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...SECONDARY);
      const apLines = doc.splitTextToSize(truncate(c.estimatedApproach || "", 45), cardW - 6);
      doc.text(apLines[0] || "", cx + 3, y + 33);
      if (apLines[1]) doc.text(apLines[1], cx + 3, y + 37);
    }
    y += 44;

    // Differentiation strategy highlight
    if (competitorIntelligence.differentiationStrategy) {
      doc.setFillColor(240, 253, 250);
      doc.setDrawColor(...TEAL);
      doc.setLineWidth(0.5);
      doc.roundedRect(M, y, cw, 14, 2, 2, "FD");
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...TEAL);
      doc.text("DIFFERENTIATION STRATEGY", M + 4, y + 5);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      const dl = doc.splitTextToSize(competitorIntelligence.differentiationStrategy, cw - 8);
      doc.text(dl.slice(0, 2), M + 4, y + 10);
      y += 18;
    }
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...SECONDARY);
    doc.text("No competitor data available.", M, y + 4);
    y += 12;
  }

  // ── Pricing Section ──
  y = sectionHead(doc, "Pricing Strategy", y);

  if (pricingAdvisor?.canEstimate && pricingAdvisor.strategies?.length > 0) {
    const strategies = pricingAdvisor.strategies.slice(0, 3);
    const sCardW = (cw - 6) / 3;

    for (let i = 0; i < 3; i++) {
      const s = strategies[i];
      if (!s) continue;
      const sx = M + i * (sCardW + 3);
      const isRec = s.approach === pricingAdvisor.recommended;

      // Card with highlight
      if (isRec) {
        doc.setFillColor(240, 253, 250);
        doc.setDrawColor(...TEAL);
        doc.setLineWidth(0.8);
      } else {
        doc.setFillColor(...CARD_BG);
        doc.setDrawColor(...CARD_BORDER);
        doc.setLineWidth(0.3);
      }
      doc.roundedRect(sx, y, sCardW, 48, 2, 2, "FD");

      // Recommended badge
      if (isRec) {
        doc.setFillColor(...TEAL);
        doc.roundedRect(sx + sCardW - 22, y + 2, 20, 5, 1.5, 1.5, "F");
        doc.setFontSize(5.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...WHITE);
        doc.text("RECOMMENDED", sx + sCardW - 21, y + 5.5);
      }

      // Strategy label
      const labelColors = [
        [59, 130, 246],  // blue - aggressive
        TEAL,            // teal - balanced
        [168, 85, 247],  // purple - premium
      ];
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...(labelColors[i] || DARK));
      doc.text(s.label || "", sx + 4, y + 8);

      // Price range
      const curr = pricingAdvisor.currency || "USD";
      if (s.estimatedRange) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...DARK);
        doc.text(`${curr} ${(s.estimatedRange.low ?? 0).toLocaleString()}`, sx + 4, y + 14);
        doc.text(`- ${(s.estimatedRange.high ?? 0).toLocaleString()}`, sx + 4, y + 18.5);
      }

      // Win prob bar
      const wp = s.winProbability ?? 0;
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...SECONDARY);
      doc.text("Win Prob.", sx + 4, y + 25);
      doc.setTextColor(...scoreColor(wp));
      doc.text(`${wp}%`, sx + sCardW - 14, y + 25);
      drawBar(doc, sx + 4, y + 27, sCardW - 8, wp / 100, scoreColor(wp), 3);

      // Margin + Risk
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...SECONDARY);
      doc.text("Margin:", sx + 4, y + 34);
      doc.setTextColor(...DARK);
      doc.text(cap(s.margin || ""), sx + 18, y + 34);

      doc.setTextColor(...SECONDARY);
      doc.text("Risk:", sx + 4, y + 38.5);
      const riskCol = (s.risk || "").toLowerCase() === "high" ? RED : (s.risk || "").toLowerCase() === "medium" ? AMBER : GREEN;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...riskCol);
      doc.text(cap(s.risk || ""), sx + 14, y + 38.5);

      // Notes
      if (s.notes) {
        doc.setFontSize(6);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(...SECONDARY);
        const nl = doc.splitTextToSize(s.notes, sCardW - 8);
        doc.text(nl[0] || "", sx + 4, y + 44);
      }
    }
    y += 52;

    // Cost drivers
    if (pricingAdvisor.costDrivers?.length > 0) {
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text("KEY COST DRIVERS", M, y + 3);
      let dy = y + 8;
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      for (const d of pricingAdvisor.costDrivers.slice(0, 4)) {
        drawDot(doc, M + 3, dy - 0.5, TEAL);
        doc.text(truncate(d, 90), M + 7, dy);
        dy += 5;
      }
    }
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...SECONDARY);
    doc.text("Insufficient financial data for pricing estimates.", M, y + 4);
    y += 10;
  }

  // ════════════════════════════════════════════════
  // PAGE 5 — ACTION PLAN
  // ════════════════════════════════════════════════
  doc.addPage();
  drawHeader(doc);
  y = 20;
  y = sectionHead(doc, "Action Plan", y);

  // ── Prioritized actions table ──
  const allActions = [
    ...((complianceAnalysis?.actionPlan || []).map((a) => ({
      num: a.priority ?? "",
      action: a.action || "",
      deadline: a.deadline || "",
      owner: a.owner || "TBD",
    }))),
    ...((riskRadar?.topActions || []).map((a, i) => {
      const prioLabels = { immediate: "Immediate", before_submission: "Pre-Submission", post_award: "Post-Award" };
      return {
        num: prioLabels[a.priority] || a.priority || String(i + 1),
        action: a.action || "",
        deadline: "",
        owner: a.responsible || "TBD",
      };
    })),
  ];

  // Deduplicate by action text
  const seen = new Set();
  const uniqueActions = allActions.filter((a) => {
    const key = a.action.toLowerCase().trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  if (uniqueActions.length > 0) {
    const actTable = autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [["#", "Action", "Deadline", "Owner"]],
      body: uniqueActions.map((a, i) => [
        String(a.num || i + 1),
        a.action,
        a.deadline,
        a.owner,
      ]),
      headStyles: {
        fillColor: TABLE_HEAD_BG,
        textColor: DARK,
        fontStyle: "bold",
        fontSize: 9,
        cellPadding: 3,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: DARK,
        cellPadding: 3,
      },
      alternateRowStyles: { fillColor: [252, 253, 255] },
      columnStyles: {
        0: { cellWidth: 12, halign: "center", fontStyle: "bold", textColor: TEAL },
        1: { cellWidth: "auto" },
        2: { cellWidth: 30 },
        3: { cellWidth: 28 },
      },
    });
    y = (actTable?.finalY || y + 10) + 8;
  }

  // ── Missing Documents Checklist ──
  if (complianceAnalysis?.missingDocuments?.length > 0) {
    const ph = doc.internal.pageSize.getHeight();
    if (y > ph - 40) { doc.addPage(); drawHeader(doc); y = 20; }

    y = sectionHead(doc, "Missing Documents", y);
    for (const d of complianceAnalysis.missingDocuments) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      // Checkbox
      doc.setDrawColor(...CARD_BORDER);
      doc.setLineWidth(0.3);
      doc.rect(M, y - 2.5, 3, 3, "S");
      doc.text(truncate(d, 85), M + 5, y);
      y += 6;
    }
    y += 4;
  }

  // ── Certification Gaps ──
  if (complianceAnalysis?.certificationGaps?.length > 0) {
    const ph = doc.internal.pageSize.getHeight();
    if (y > ph - 40) { doc.addPage(); drawHeader(doc); y = 20; }

    y = sectionHead(doc, "Certification Gaps", y);
    for (const c of complianceAnalysis.certificationGaps) {
      drawDot(doc, M + 2, y - 0.5, AMBER);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      doc.text(truncate(c, 85), M + 6, y);
      y += 6;
    }
    y += 4;
  }

  // ── Key Dates Timeline ──
  if (keyDates?.length > 0) {
    const ph = doc.internal.pageSize.getHeight();
    if (y > ph - 30) { doc.addPage(); drawHeader(doc); y = 20; }

    y = sectionHead(doc, "Key Dates", y);
    const timelineY = y + 3;
    const dates = keyDates.slice(0, 6);
    const segW = (cw - 10) / Math.max(dates.length - 1, 1);

    // Horizontal line
    doc.setDrawColor(...CARD_BORDER);
    doc.setLineWidth(0.5);
    doc.line(M + 5, timelineY, M + 5 + segW * (dates.length - 1), timelineY);

    for (let i = 0; i < dates.length; i++) {
      const dx = M + 5 + i * segW;
      // Node dot
      drawDot(doc, dx, timelineY, TEAL, 2);
      // Date
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...TEAL);
      const dateText = truncate(dates[i].date || "", 14);
      doc.text(dateText, dx - doc.getTextWidth(dateText) / 2, timelineY - 4);
      // Event
      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...DARK);
      const evLines = doc.splitTextToSize(truncate(dates[i].event || "", 22), segW - 4);
      doc.text(evLines[0] || "", dx - (doc.getTextWidth(evLines[0] || "") / 2), timelineY + 5);
      if (evLines[1]) {
        doc.text(evLines[1], dx - (doc.getTextWidth(evLines[1]) / 2), timelineY + 9);
      }
    }
  }

  // ── FOOTERS (all pages) ──
  drawFooters(doc);

  // ── SAVE ──
  const baseName = (summary?.projectName || fileName || "Analysis").replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9 -]/g, "").trim().replace(/\s+/g, "-");
  doc.save(`${baseName}-Bidlyze-Report.pdf`);
}
